export default interface GuildConfig {
    prefix: string,
    welcomeMessage: string,
    starboardChannel: string,
    muteRole: string,
    msgLogChannel: string,
    suggestionChannel: string,
    disabledCommands: string[],
    useExpSystem: boolean,
    showLevelUp: boolean,
    boosterBenefits: boolean,
    customEmote: string,
    starReactions: number,

    modLogChannel: string,
    automodCensoredWords: boolean,
    automodCensoredWordsList: string[],
    automodRepeatedText: boolean,
    automodLinks: boolean,
    automodCaps: boolean,
    automodExcessiveEmojis: boolean,
    automodExcessiveSpoilers: boolean,
    automodExcessiveMentions: boolean,
}